import { TarotCard } from '../types/fal';

export const tarotDeck: TarotCard[] = [
  { id: 'major-01', name: 'Deli', arcana: 'major', keywords: ['yeni başlangıçlar', 'spontanlık', 'özgürlük', 'risk'] },
  { id: 'major-02', name: 'Büyücü', arcana: 'major', keywords: ['irade gücü', 'yaratıcılık', 'beceri', 'fırsat'] },
  { id: 'major-03', name: 'Azize', arcana: 'major', keywords: ['sezgi', 'gizem', 'iç ses', 'bilgelik'] },
  { id: 'major-04', name: 'İmparatoriçe', arcana: 'major', keywords: ['bereket', 'bolluk', 'annelik', 'doğa'] },
  { id: 'major-05', name: 'İmparator', arcana: 'major', keywords: ['otorite', 'yapı', 'kontrol', 'istikrar'] },
  { id: 'major-06', name: 'Aziz', arcana: 'major', keywords: ['gelenek', 'rehberlik', 'inanç', 'öğreti'] },
  { id: 'major-07', name: 'Aşıklar', arcana: 'major', keywords: ['seçim', 'uyum', 'aşk', 'değerler'] },
  { id: 'major-08', name: 'Savaş Arabası', arcana: 'major', keywords: ['kararlılık', 'irade', 'zafer', 'yön'] },
  { id: 'major-09', name: 'Güç', arcana: 'major', keywords: ['cesaret', 'sabır', 'şefkat', 'iç güç'] },
  { id: 'major-10', name: 'Ermiş', arcana: 'major', keywords: ['içe dönüş', 'arayış', 'yalnızlık', 'rehberlik'] },
  { id: 'major-11', name: 'Kader Çarkı', arcana: 'major', keywords: ['döngüler', 'kader', 'değişim', 'fırsat'] },
  { id: 'major-12', name: 'Adalet', arcana: 'major', keywords: ['denge', 'gerçek', 'adalet', 'sonuçlar'] },
  { id: 'major-13', name: 'Asılan Adam', arcana: 'major', keywords: ['teslimiyet', 'bekleyiş', 'yeni bakış açısı', 'fedakarlık'] },
  { id: 'major-14', name: 'Ölüm', arcana: 'major', keywords: ['dönüşüm', 'bitiş', 'yeni başlangıç', 'bırakma'] },
  { id: 'major-15', name: 'Denge', arcana: 'major', keywords: ['uyum', 'sabır', 'ölçülülük', 'denge'] },
  { id: 'major-16', name: 'Şeytan', arcana: 'major', keywords: ['bağımlılık', 'gölge', 'maddiyat', 'esaret'] },
  { id: 'major-17', name: 'Kule', arcana: 'major', keywords: ['ani değişim', 'yıkım', 'uyanış', 'kriz'] },
  { id: 'major-18', name: 'Yıldız', arcana: 'major', keywords: ['umut', 'ilham', 'iyileşme', 'inanç'] },
  { id: 'major-19', name: 'Ay', arcana: 'major', keywords: ['belirsizlik', 'korkular', 'bilinçaltı', 'yanılsama'] },
  { id: 'major-20', name: 'Güneş', arcana: 'major', keywords: ['mutluluk', 'başarı', 'canlılık', 'netlik'] },
  { id: 'major-21', name: 'Mahkeme', arcana: 'major', keywords: ['uyanış', 'yenilenme', 'karar anı', 'affediş'] },
  { id: 'major-22', name: 'Dünya', arcana: 'major', keywords: ['tamamlanma', 'bütünlük', 'başarı', 'döngü sonu'] },
  { id: 'minor-01', name: 'As Değnek', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-02', name: 'İki Değnek', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-03', name: 'Üç Değnek', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-04', name: 'Dört Değnek', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-05', name: 'Beş Değnek', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-06', name: 'Altı Değnek', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-07', name: 'Yedi Değnek', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-08', name: 'Sekiz Değnek', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-09', name: 'Dokuz Değnek', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-10', name: 'On Değnek', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-11', name: 'Değnek Vale', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-12', name: 'Değnek Şövalye', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-13', name: 'Değnek Kraliçe', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-14', name: 'Değnek Kral', arcana: 'minor', keywords: ['tutku', 'enerji', 'eylem', 'yaratıcılık'] },
  { id: 'minor-15', name: 'As Kupa', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-16', name: 'İki Kupa', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-17', name: 'Üç Kupa', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-18', name: 'Dört Kupa', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-19', name: 'Beş Kupa', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-20', name: 'Altı Kupa', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-21', name: 'Yedi Kupa', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-22', name: 'Sekiz Kupa', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-23', name: 'Dokuz Kupa', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-24', name: 'On Kupa', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-25', name: 'Kupa Vale', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-26', name: 'Kupa Şövalye', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-27', name: 'Kupa Kraliçe', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-28', name: 'Kupa Kral', arcana: 'minor', keywords: ['duygular', 'ilişkiler', 'sezgi', 'aşk'] },
  { id: 'minor-29', name: 'As Kılıç', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-30', name: 'İki Kılıç', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-31', name: 'Üç Kılıç', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-32', name: 'Dört Kılıç', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-33', name: 'Beş Kılıç', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-34', name: 'Altı Kılıç', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-35', name: 'Yedi Kılıç', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-36', name: 'Sekiz Kılıç', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-37', name: 'Dokuz Kılıç', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-38', name: 'On Kılıç', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-39', name: 'Kılıç Vale', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-40', name: 'Kılıç Şövalye', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-41', name: 'Kılıç Kraliçe', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-42', name: 'Kılıç Kral', arcana: 'minor', keywords: ['zihin', 'düşünce', 'çatışma', 'gerçek'] },
  { id: 'minor-43', name: 'As Tılsım', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
  { id: 'minor-44', name: 'İki Tılsım', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
  { id: 'minor-45', name: 'Üç Tılsım', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
  { id: 'minor-46', name: 'Dört Tılsım', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
  { id: 'minor-47', name: 'Beş Tılsım', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
  { id: 'minor-48', name: 'Altı Tılsım', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
  { id: 'minor-49', name: 'Yedi Tılsım', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
  { id: 'minor-50', name: 'Sekiz Tılsım', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
  { id: 'minor-51', name: 'Dokuz Tılsım', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
  { id: 'minor-52', name: 'On Tılsım', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
  { id: 'minor-53', name: 'Tılsım Vale', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
  { id: 'minor-54', name: 'Tılsım Şövalye', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
  { id: 'minor-55', name: 'Tılsım Kraliçe', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
  { id: 'minor-56', name: 'Tılsım Kral', arcana: 'minor', keywords: ['maddiyat', 'kariyer', 'kaynaklar', 'güvenlik'] },
];

export function shuffleDeck(): TarotCard[] {
  const deck = [...tarotDeck];
  for (let i = deck.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [deck[i], deck[j]] = [deck[j], deck[i]];
  }
  return deck;
}
